spring.cloud.function.definition=employeeProducer;employeeResultConsumer

# --- PRODUTOR (Saida) ---
# Envia para a exchange 'employee-events'
spring.cloud.stream.bindings.employeeProducer-out-0.destination=employee-events

# --- CONSUMIDOR (Entrada) ---
# Escuta a exchange 'employee-results' (onde Payroll e DB respondem)
spring.cloud.stream.bindings.employeeResultConsumer-in-0.destination=employee-results
spring.cloud.stream.bindings.employeeResultConsumer-in-0.group=crud-group