spring.cloud.stream.default-binder=kafka
spring.cloud.stream.kafka.binder.brokers=localhost:9092
spring.cloud.stream.kafka.binder.replication-factor=1

# --- PRODUTOR (Inicio da Saga) ---
spring.cloud.stream.bindings.employeeProducer-out-0.destination=employee-events

# --- CONSUMIDOR (Fim da Saga / Compensacoes) ---
spring.cloud.stream.bindings.employeeResultConsumer-in-0.destination=employee-results
spring.cloud.stream.bindings.employeeResultConsumer-in-0.group=crud-group

spring.cloud.stream.kafka.bindings.employeeResultConsumer-in-0.consumer.startOffset=latest