spring.cloud.stream.default-binder=rabbit
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

# --- Configuracao Avancada do RabbitMQ ---

# PRODUTOR:
# 1. exchangeType=topic: Permite roteamento flexivel
# 2. routingKeyExpression: Define a chave 'employee.created' para a mensagem
spring.cloud.stream.rabbit.bindings.employeeProducer-out-0.producer.exchangeType=topic
spring.cloud.stream.rabbit.bindings.employeeProducer-out-0.producer.routingKeyExpression='employee.created'

# CONSUMIDOR:
# 1. exchangeType=topic: Necessario para ouvir exchanges do tipo Topic
# 2. bindingRoutingKey=#: O curinga '#' diz "Quero ouvir TUDO dessa exchange"
spring.cloud.stream.rabbit.bindings.employeeResultConsumer-in-0.consumer.exchangeType=topic
spring.cloud.stream.rabbit.bindings.employeeResultConsumer-in-0.consumer.bindingRoutingKey=#