# Define as duas funções ativas (Inicio e Processamento)
spring.cloud.function.definition=orchestratorTrigger;orchestratorProcess

# --- 1. CONFIG DO TRIGGER (Inicio) ---
# Saída padrão (será sobrescrita pelo header, mas o Spring pede um default)
spring.cloud.stream.bindings.orchestratorTrigger-out-0.destination=payroll-commands

# --- 2. CONFIG DO PROCESSADOR (Meio/Fim) ---
# Entrada: Ouve TODAS as respostas (Saga Replies)
spring.cloud.stream.bindings.orchestratorProcess-in-0.destination=saga-replies
spring.cloud.stream.bindings.orchestratorProcess-in-0.group=crud-orchestrator-group

# Saida: Default (sera sobrescrita dinamicamente pelo header para inventory-commands ou db-commands)
spring.cloud.stream.bindings.orchestratorProcess-out-0.destination=orchestrator-sink-default