spring.application.name=crud-service
server.port=8081

# --- DESATIVA O CONFIG SERVER ---
spring.cloud.config.enabled=false
spring.config.import=optional:file:.env

# --- JSON ---
spring.cloud.stream.default.content-type=application/json

# --- Service Discovery (Eureka) ---
eureka.client.service-url.defaultZone=http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# --- Logging ---
logging.level.com.netflix.discovery=INFO
logging.level.org.springframework.cloud.netflix.eureka=INFO
# Deixe DEBUG no AMQP para vermos a criação das filas
logging.level.org.springframework.amqp=DEBUG 
logging.level.org.springframework.cloud.stream=DEBUG

spring.r2dbc.url=r2dbc:postgresql://localhost:5433/db_service
spring.r2dbc.username=postgres
spring.r2dbc.password=password

# --- Tracing ---
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# --- Resilience4j Configs ---
resilience4j.circuitbreaker.instances.dbServiceCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.dbServiceCircuitBreaker.sliding-window-size=10
resilience4j.circuitbreaker.instances.dbServiceCircuitBreaker.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.dbServiceCircuitBreaker.wait-duration-in-open-state=20s
resilience4j.circuitbreaker.instances.dbServiceCircuitBreaker.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.aiServiceCircuitBreaker.failure-rate-threshold=60
resilience4j.circuitbreaker.instances.aiServiceCircuitBreaker.sliding-window-size=5
resilience4j.circuitbreaker.instances.aiServiceCircuitBreaker.wait-duration-in-open-state=30s
resilience4j.retry.instances.dbServiceRetry.max-attempts=3
resilience4j.retry.instances.dbServiceRetry.wait-duration=1s
resilience4j.retry.instances.aiServiceRetry.max-attempts=2
resilience4j.retry.instances.aiServiceRetry.wait-duration=2s